drop table if exists orderbook;

create table orderbook (
    id bigserial primary key,
    source_row_number numeric,
    banner text,
    status text,
    eta date,
    eta_vs_crd date,
    coverage_performance text,
    week_commencing date,
    age_division text,
    brand text,
    confirmed_wholesale numeric,
    available_wholesale numeric,
    sold_to_name text,
    sold_to_code text,
    ship_to_name text,
    ship_to_code text,
    order_entry_date date,
    customer_request_date date,
    requested_month text,
    customer_confirmed_date date,
    season text,
    order_type text,
    always_available_product_indicator text,
    distribution_method text,
    shipment_type text,
    sales_order_number text,
    sales_order_line_item_number numeric,
    po_number text,
    contact_name text,
    gender text,
    category text,
    sub_category text,
    division text,
    style_color text,
    style_name text,
    color_description text,
    replica_indicator text,
    launch_date date,
    launch_code text,
    campaign text,
    order_status text,
    ordered_quantity numeric,
    confirmed_quantity numeric,
    remaining_to_ship_quantity numeric,
    remaining_to_ship_percentage numeric,
    available_quantity numeric,
    percentage_available_of_order numeric,
    not_available_quantity numeric,
    total_booked_quantity numeric,
    not_covered_quantity numeric,
    rejected_quantity numeric,
    rejected_date text,
    rejection_reason text,
    nike_eta date,
    planned_delivery_date text,
    first_possible_delivery_date_drs_method_only date,
    planned_goods_issue_date date,
    container_number text,
    packlist_dc_shipment_id_drs text,
    shipped_carton_quantity text,
    remaining_to_ship_estimated_dc_carton_quantity text,
    unshippable_order_reason text,
    delivery_schedule_block_description text,
    wholesale_price_transaction_currency numeric,
    net_price_transaction_currency numeric,
    transaction_currency text,
    wholesale_price_usd numeric,
    net_price_usd numeric,
    msrp text,
    discount_percentage numeric,
    harmonized_tax_code text,
    wholesale_us_confirmed text,
    wholesale_us_available text,
    report_wholesale_value numeric
);

create index idx_orderbook_banner on orderbook (banner);
create index idx_orderbook_season on orderbook (season);
create index idx_orderbook_status on orderbook (status);
create index idx_orderbook_order_type on orderbook (order_type);
create index idx_orderbook_requested_month on orderbook (requested_month);
